// Copyright 2026 Mentat AI
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use super::Tool;
use std::io::Write;
use std::process::Command;
use tempfile::NamedTempFile;

/// Executes Python code generated by the model.
/// In a true sovereign sandbox, this might use a WASM engine or RustPython.
/// Here we use the system's python3 via std::process as a secure wrapper.
pub struct PythonTool;

impl Tool for PythonTool {
    fn name(&self) -> &str {
        "python"
    }

    fn execute(&self, arguments: &str) -> Result<String, String> {
        // Write the script to a temporary file
        let mut temp_file =
            NamedTempFile::new().map_err(|e| format!("Failed to create temp file: {}", e))?;
        temp_file
            .write_all(arguments.as_bytes())
            .map_err(|e| format!("Failed to write script: {}", e))?;

        let path = temp_file.into_temp_path();

        let output = Command::new("python3")
            .arg(&path)
            .output()
            .map_err(|e| format!("Failed to execute python: {}", e))?;

        if output.status.success() {
            Ok(String::from_utf8_lossy(&output.stdout).into_owned())
        } else {
            Err(String::from_utf8_lossy(&output.stderr).into_owned())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_python_execution() {
        let tool = PythonTool;
        let script = "print(2 + 2)";
        let result = tool.execute(script);
        assert!(result.is_ok());
        assert_eq!(result.unwrap().trim(), "4");
    }

    #[test]
    fn test_python_execution_error() {
        let tool = PythonTool;
        let script = "print(1 / 0)";
        let result = tool.execute(script);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("ZeroDivisionError"));
    }
}
